name: Node.js CI

on:
  push:
    branches: ["main"]
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - uses: actions/checkout@v4

      - name: Use Node ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm
          cache-dependency-path: package-lock.json

      - name: Debug workspace
        run: |
          pwd
          ls -la

      - name: Install dependencies
        run: npm ci

      - name: Run backend server
        run: npm run start --if-present

      - name: Discord success-report
        if: ${{ success() }}
        uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          noprefix: true
          title: "✅ Webshop server-start succeeded"
          color: 0x366336
          username: Github Actions

      - name: Discord failure-report
        if: ${{ failure() }}
        uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          noprefix: true
          title: "❌ Webshop server-start failed"
          color: 0x4d1717
          username: Github Actions
